function start(){function y(a){chrome.storage.local.get(["is-active","reload-last-date","reload-enabled","reload-interval"],function(b){p=!!b["is-active"];var c=Math.max(parseInt(b["reload-interval"]||6E4,10),2E3),e=Date.now()-parseInt(b["reload-last-date"]||0,10),c=1E3*Math.round(Math.max(c-e,0)/1E3);a({is_active:p,time:b["reload-enabled"]?c:null})})}function D(){for(var a=document.getElementsByClassName("button"),b=0;b<a.length;b++)if(-1!=a[b].textContent.indexOf("Continue"))return!0;return!1}function z(){var a=
document.getElementsByClassName("container");return a.length?(a=a[0].textContent.toLowerCase(),-1!=a.indexOf("no tasks")&&-1==a.indexOf("you have not rated tasks")):!1}function E(){var a={},b=document.getElementsByClassName("button");if(b.length)for(var c=0;c<b.length;c++){var e=b[c],d;d=e.parentNode.textContent;d=d.replace(e.textContent,"");if(d=d.replace(/(?:(?:^|\n)\s+|\s+(?:$|\n))/g,"").replace(/\s+/g," "))a[d]=e.href}return a}function F(){var a=[],b=document.getElementsByClassName("ewok-rater-device-suggestions");
b.length||(b=document.getElementsByClassName("ewok-rater-task-header"));b.length||(b=document.getElementsByClassName("container"));b.length&&(b=b[0].textContent.toLowerCase(),-1!=b.indexOf("android")&&a.push("Android Mobile"),-1!=b.indexOf("iphone")&&a.push("iPhone"),-1!=b.indexOf("ipad")&&a.push("iPad"));return a}function A(a){a&&!f?g():!a&&f&&(window.clearTimeout(f),f=0,g())}function g(){y(function(a){a=null!==a.time?a.time:null;if(null===a)window.clearTimeout(f),f=0;else if(0===a){window.clearTimeout(f);
f=0;try{h.postMessage({type:"index-will-reload"})}catch(b){}location.reload()}else f=window.setTimeout(g,1E3);var c;c=document.title||"";c=c.split(" \u2022 ")[0];0===c.indexOf("\u25b6 ")&&(c=c.split(2));0===c.indexOf("\u25b7 ")&&(c=c.split(2));if(null===a)document.title=c;else if(c&&"undefined"!==typeof a){var e=Math.max(Math.round(a/1E3),0);a=c+" \u2022 ";var d=e,k=0>d,d=Math.abs(Number(d));c=Math.floor(d/3600);e=Math.floor(d%3600/60);d=Math.floor(d%3600%60);k=(k?"-":"")+(0<c?c+":":"");k+=0<c?(10>
e?"0":"")+e+":":e+":";k+=(10>d?"0":"")+d;c=a+k;document.title=c}})}var f,q=Date.now();document.body.setAttribute("current-ra",q);var h=chrome.runtime.connect({name:"ra-index-page"}),p=!1;h.onMessage.addListener(function(a){if("post-user-totals"==a.type){p=!!a.is_active;var b=a.totals;a=document.title||"";0===a.indexOf("\u25b6 ")&&(a=a.slice(2));0===a.indexOf("\u25b7 ")&&(a=a.slice(2));p&&(b=b&&b.surplus&&b.surplus.session,null!==b&&"undefined"!==typeof b&&(a=(0<=b?"\u25b7":"\u25b6")+" "+a));a!=document.title&&
(document.title=a)}});chrome.runtime.sendMessage({type:"get-user-totals"});var B=atob("c3Vic2NyaXB0aW9u");chrome.storage.local.get(["is-active","lastNRT","reload-acquire-enabled","reload-acquire-mode","reload-enabled","reload-last-types","reload-last-mobile-types","reload-monitor-changes","reload-types",B,"reload-last-date","reload-interval","reload-status-update"],function(a){function b(a){var b=[],c;for(c in a)a=c.toLowerCase(),-1!=a.indexOf("result review")?0!=(Math.pow(2,0)&e)&&b.push(c):-1!=
a.indexOf("experimental")?-1!=a.indexOf("(experimental)")?0!=(Math.pow(2,1)&e)&&b.push(c):0!=(Math.pow(2,2)&e)&&b.push(c):-1!=a.indexOf("side by side")&&(-1!=a.indexOf("(side by side)")?0!=(Math.pow(2,4)&e)&&b.push(c):0!=(Math.pow(2,3)&e)&&b.push(c));return b}function c(){r=v||{};var a=f[t[0]];a&&(window.location.href=a);w=!0}h.postMessage({type:"index-page-did-load",isNRT:z()});p=!!a["is-active"];if(a[B]){var e=a["reload-types"]||31,d=a.lastNRT||0,f=E(),g=!!a["reload-acquire-enabled"],q=g&&!!a["reload-acquire-mode"]&&
p,v=a["reload-last-types"]||null,t=b(f),r=Object.keys(f),n=Date.now(),u=Math.max(parseInt(a["reload-interval"]||6E4,10),2E3),l=n-(a["reload-last-date"]||0),m=!!a["reload-status-update"],C=!!a["reload-monitor-changes"];a=a["reload-last-mobile-types"]||null;var x=F();if(0>l||l>=u+24E4)chrome.storage.local.remove("lastNRT"),a=v=null,d=0;var w=!1,u=!1;if(D())g&&d&&(document.getElementsByClassName("button")[0].click(),w=!0);else if(r.length&&m)h.postMessage({type:"got-new-types",types:r,needs_status_update:m}),
u=!0;else if(r.length){m=[];for(l=0;l<t.length;l++)null!==v&&-1==v.indexOf(t[l])&&m.push(t[l]);if(q&&t.length)c();else if(Object.keys(m).length)if(g&&d)c();else if(C||d)h.postMessage({type:"got-new-types",types:m}),u=!0}else z()&&(chrome.storage.local.set({lastNRT:n}),h.postMessage({type:"got-no-rating-tasks",needs_status_update:m}));chrome.storage.local.set({"reload-last-types":r,"reload-last-mobile-types":x,"reload-last-date":n,"reload-status-update":!1},function(){y(function(a){A(!w&&null!==a.time)})});
w||u||0!=(Math.pow(2,5)&e)&&null!==a&&x.length>a.length&&(C||d)&&h.postMessage({type:"got-new-types",types:x})}});chrome.storage.onChanged.addListener(function(a,b){a["reload-enabled"]?chrome.storage.local.set({"reload-last-date":Date.now()},function(){chrome.storage.local.remove(["reload-last-types","reload-last-mobile-types"],function(){A(a["reload-enabled"].newValue)})}):a["reload-interval"]&&chrome.storage.local.set({"reload-last-date":Date.now()},function(){chrome.storage.local.get("reload-enabled",
function(a){a["reload-enabled"]&&g()})})});for(var q=document.getElementsByClassName("button"),n=0;n<q.length;n++)q[n].addEventListener("click",function(){window.clearTimeout(f);f=0});-1!=document.body.textContent.indexOf("An internal error occurred.")&&(document.title="Error")}"complete"==document.readyState?start():document.addEventListener("DOMContentLoaded",start);
