(function(){function I(){try{var h=["querybar-collapsed","querybar-state","show-querybar",J];chrome.storage.local.get(h,function(f){v=!!f["querybar-collapsed"];f[J]&&!1!==f["show-querybar"]&&K(f["querybar-state"])});chrome.storage.onChanged.addListener(function(f){f["show-querybar"]&&(L=!1!==f["show-querybar"].newValue,chrome.storage.local.get(h,function(f){f[J]||(L=!1);f=f["querybar-state"]||{};l?l(L?f:null):L&&K(f)}))})}catch(f){console.log("Error in onLoad: "+f)}}function K(h){function f(a,d){d=
d.toUpperCase();do if(a.nodeName===d)return a;while(a=a.parentNode);return null}function n(a){var d,c;d=a.substring(1,3);c=a.substring(3,5);a=a.substring(5,7);d=parseInt(d,16);c=parseInt(c,16);a=parseInt(a,16);return 105>255-(.299*d+.587*c+.114*a)?"#000000":"#ffffff"}function U(a,d){var c=R(a);if(c.length){for(var g=k&&k.items||[],e=0;e<c.length;e++)g.push({term:c[e]});k.items=g;k.selectedTerms||(k.selectedTerms=[]);for(e=0;e<c.length;e++)g=c[e],t(g)&&q(k.selectedTerms,g);l(k,!0);G(k,function(){l(k,
!1);d&&d()})}}function z(a,d){var c=k||{},g=f(a.target,"TD");if(g&&"INPUT"!=a.target.tagName){for(var e=document.getElementsByClassName("ra-querybar-term"),u=-1,B=0;B<e.length;B++)if(e[B]==g){u=B;break}for(var b,B=Math.min(u,m),u=Math.max(u,m);B<=u;B++)g=c.items[B].term,c.selectedTerms||(c.selectedTerms=[]),b|=y(c.selectedTerms,g);b&&(S=0,l(c,d))}}function V(a){function d(){p();c.className="ra-selected";var a=document.getElementById("ra-querybar-add-cell"),d;if(a)d=document.getElementById("ra-querybar-right-add"),
a.style.display="table-cell",d.style.display="table-cell";else{var e=function(c){U(g.value);g.value="";a.style.display="none";d.style.display="none";d.className="disabled";k.className="";O();c.preventDefault();return!1},a=document.createElement("td");a.id="ra-querybar-add-cell";var g=document.createElement("input");g.type="text";g.style.width="196px";d=document.createElement("td");d.id="ra-querybar-right-add";d.textContent="+";a.addEventListener("input",function(a){a=document.getElementById("ra-querybar-add-cell").getElementsByTagName("input")[0].value.trim().length;
d.className=a?"":"disabled"});var k=c;g.addEventListener("keydown",function(a){switch(a.which){case 27:k.click();break;case 13:b()&&(R(g.value).length?d.click():k.click())}});d.addEventListener("click",e);d.addEventListener("contextmenu",e);a.appendChild(g);e=c.parentNode;e.appendChild(a);e.appendChild(d)}e=a.getElementsByTagName("input")[0];(function(a){var c="";window.getSelection?c=window.getSelection().toString():document.selection&&"Control"!=document.selection.type&&(c=document.selection.createRange().text);
c=c.trim().split(" ");c.length&&(a.value=c.slice(0,3).join(" "));d.className=a.value.length?"":"disabled"})(e);e.focus();O()}var c=f(a.target,"TD");if(!c||"INPUT"==a.target.tagName)return a.preventDefault(),!1;for(var g=document.getElementsByClassName("ra-querybar-term"),e=0;e<g.length&&g[e]!=c;e++);"ra-querybar-term"!=c.className&&("ra-querybar-left-add"==c.id?"ra-selected"!=c.className?d():A():"ra-querybar-collapse"==c.id&&I());a.preventDefault();return!1}function J(a,d){for(var c=0;c<a.length;c++)if(a[c].term==
d)return c;return-1}function q(a,d){if(-1==a.indexOf(d)){var c=a.indexOf(null);-1!=c?a.splice(c,1,d):a.push(d);return!0}return!1}function b(){var a=document.getElementById("ra-querybar-add-cell");return!(!a||"none"==a.style.display)}function w(a){return a&&a.length&&0==(/[!-~]+/.exec(a)||"").length?!0:!a||2>a.length?!1:!0}function t(a){return w(a)&&-1==X.indexOf(a)?!0:!1}function y(a,d){if(!a||!a.length)return!1;for(var c=0,g=a.length-1;0<=g;g--)d==a[g]&&(a.splice(g,1,null),c++);return!!c}function A(){document.getElementById("ra-querybar-left-add").className=
"";var a=document.getElementById("ra-querybar-add-cell");a&&(a.style.display="none",a.getElementsByTagName("input")[0].value="",document.getElementById("ra-querybar-right-add").style.display="none");O()}function p(){for(var a=P.getElementsByClassName("ra-querybar-term"),d=k&&k.items||[],c=0;c<a.length;c++){var g=a[c],e=g.getElementsByTagName("input");if(e.length)for(var u=0;u<e.length;u++)e[u].parentNode.removeChild(e[u]);(e=d[c])&&e.term&&(g.textContent=e.term)}}function G(a,d){try{chrome.storage.onChanged.removeListener(F),
chrome.storage.local.set({"querybar-state":a},function(){chrome.storage.onChanged.addListener(F);d()})}catch(c){console.log("Error saving QB state: "+c.message)}}function H(a,d){var c=k||{},g=f(a.target,"TD");if(g&&"INPUT"!=a.target.tagName){for(var e=document.getElementsByClassName("ra-querybar-term"),u=-1,b=0;b<e.length;b++)if(e[b]==g){u=b;break}for(var p,b=Math.min(u,m),u=Math.max(u,m);b<=u;b++)g=c.items[b].term,c.selectedTerms||(c.selectedTerms=[]),p|=q(c.selectedTerms,g);p&&(S=1,l(c,d))}}function F(a){L&&
(a["querybar-collapsed"]&&(v=a["querybar-collapsed"].newValue,l(k)),a["querybar-state"]&&l(a["querybar-state"].newValue))}function R(a){var d=[];if(a&&a.length&&0==(/[!-~]+/.exec(a)||"").length)for(g=(a||"").replace(/\s+/,""),c=0;c<g.length;c++)d.push(g[c]);else{a=(a||"").trim().split(/\s+/);for(var c=0;c<a.length;c++){var g=a[c].trim().replace(/^[,:'"]+|[.,?!;:'"]+$/g,"");g.length&&d.push(g)}}return d}function I(){v=!v;chrome.storage.local.set({"querybar-collapsed":v});A();l(k)}function K(a,d){var c=
k||{},g=f(a.target,"TD");if(g&&"INPUT"!=a.target.tagName){for(var e=document.getElementsByClassName("ra-querybar-term"),b=-1,p=0;p<e.length;p++)if(e[p]==g){b=p;break}g=c.items[b].term;c.selectedTerms||(c.selectedTerms=[]);-1==c.selectedTerms.indexOf(g)?H(a,d):z(a,d)}}function O(){var a=document.getElementById("ra-querybar-left-add");if(a){var d=b()?"<":"+",c=v?"none":"table-cell";d!=a.textContent&&(a.textContent=d);c!=a.style.display&&(a.style.display=c)}}var Y="#99ff99 #ff9999 #a0ffff #ffabff #ffc266 #b2d1ff".split(" "),
X="an the and but or nor at by for in of on to as is it so are be AN THE AND BUT OR NOR AT BY FOR IN OF ON TO AS IS IT SO ARE BE".split(" "),C=null,S=0,m=-1,D=-1,E,W=0,k={},M=null,N=0,Q=0;E=new Z(null,"RA");E.setMatchType("open");var T=document.createElement("div");T.id="ra-querybar";document.body.insertBefore(T,document.body.firstChild);var r=document.createElement("table"),P=r.appendChild(document.createElement("tbody")).appendChild(document.createElement("tr"));T.appendChild(r);l=function(a,d){var c=
document.getElementById("ra-querybar"),g="table-cell";if(null===a||"undefined"===typeof a)g="none",E.remove(),a=null;else{if(!document.getElementById("ra-querybar-collapse")){var e=document.createElement("td");e.id="ra-querybar-collapse";P.appendChild(e)}for(var b=a&&a.items||[],f=a&&a.selectedTerms||[],p=document.getElementsByClassName("ra-querybar-term"),h=x.get("querybar-color-list")||Y,y=[],t=0;t<p.length;t++){var e=p[t],m=e.getElementsByTagName("input");m.length&&m[0].parentNode.removeChild(m[0]);
var m=t<b.length?b[t]:null,l="none";if(null!==m){m.term!=e.textContent&&(e.textContent=m.term);var A=f.indexOf(m.term),r="transparent",q="#000000";-1!=A&&(r=h[A%h.length],q=n(r),w(m.term)&&y.push({term:m.term,color:r,textColor:q}));r!=e.style.backgroundColor&&(e.style.backgroundColor=r);q!=e.style.color&&(e.style.color=q);v||(l="table-cell")}l!=e.style.display&&(e.style.display=l)}l=document.getElementById("ra-querybar-left-add");if(p.length<b.length)for(t=p.length;t<b.length;t++)m=b[t],e=document.createElement("td"),
e.className="ra-querybar-term",e.textContent=m.term,P.insertBefore(e,l),A=f.indexOf(m.term),-1!=A&&(r=h[A%h.length],q=n(r),w(m.term)&&y.push({term:m.term,color:r,textColor:q}),r!=e.style.backgroundColor&&(e.style.backgroundColor=r),q!=e.style.color&&(e.style.color=q)),v&&(e.style.display="none");l||(l=document.createElement("td"),l.id="ra-querybar-left-add",P.appendChild(l));O();if(e=document.getElementById("ra-querybar-collapse")){b=v?">":"<";if(!(f=v))for(f=0,p=document.getElementsByClassName("ra-querybar-term"),
h=0;h<p.length;h++)"none"!=p[h].style.display&&f++;f=f?"table-cell":"none";b!=e.textContent&&(e.textContent=b);f!=e.style.display&&(e.style.display=f)}y&&!d&&(document.hidden?M=y:(y.length?E.applyItems(y):E.remove(),M=null))}c&&g!=c.style.display&&(c.style.display=g);k=a};r.addEventListener("click",V,!0);r.addEventListener("contextmenu",function(a){function d(a,d){var e=a.trim(),g=c.selectedTerms||[];y(g,t);e.length?(c.items.splice(d,1,{term:e}),q(g,e)):c.items.splice(d,1);c.selectedTerms=g;G(c,function(){l(c)})}
if("ra-querybar-term"!=a.target.className)return V(a),a.preventDefault(),!1;for(var c=k||{},g=f(a.target,"TD"),e=document.getElementsByClassName("ra-querybar-term"),b=-1,h=0;h<e.length;h++)if(e[h]==g){b=h;break}var t=c.items[b].term;if(-1!=b){p();A();var w=document.createElement("input");w.id="ra-querybar-edit-field";w.style.width=Math.max(96,g.clientWidth)+"px";g.firstChild&&g.removeChild(g.firstChild);g.appendChild(w);w.value=t;w.select();w.addEventListener("keydown",function(a){switch(a.which){case 27:l(c);
break;case 13:d(w.value,b)}});m=D=-1}a.preventDefault();return!1},!0);r.addEventListener("mousedown",function(a){if("INPUT"!=a.toElement.tagName){if(0!=a.button||"ra-querybar-term"!=a.target.className)return a.preventDefault(),!1;for(var d=f(a.target,"TD"),c=d,g=0;c&&(c=c.previousSibling);)3==c.nodeType&&/^\s*$/.test(c.data)||g++;m=g-1;N=a.ctrlKey||a.metaKey;Q=!!a.shiftKey;C=null;N||Q||(document.getElementById("ra-querybar-edit-field")?l(k):d&&"ra-querybar-term"==d.className&&K(a,!1));a.preventDefault();
return!1}},!0);r.addEventListener("mouseout",function(a){if(-1!=m){var d=a.toElement,c=0!=d.className.indexOf("ra-querybar")&&0!=d.id.indexOf("ra-querybar");if(!d||"ra-querybar-left-add"==d.id||c)N&&42<window.innerHeight-a.y&&(d=k.items.splice(m,1),y(k.selectedTerms,d.term)),G(k,function(){l(k,!1)}),m=D=-1}a.preventDefault();return!1},!0);r.addEventListener("mouseover",function(a){var d=a.fromElement&&f(a.fromElement,"TD"),c=a.toElement&&f(a.toElement,"TD"),g=f(a.target,"TD");if(g&&d!==c&&!g.getElementsByTagName("input").length&&
"ra-querybar-term"==g.className){for(var c=document.getElementsByClassName("ra-querybar-term"),e=-1,d=0;d<c.length;d++)if(c[d]==g){e=d;break}d=D!=e;D=e;if(-1!=m&&d)if(C||(C=k.items[m].term),N&&C){var b=k.items.splice(m,1)[0];k.items.splice(e,0,b);m=D=e;G(k,function(){l(k,!0)})}else if(Q){if(d=J(k.items,C),g=(b=-1!=d&&k.items[d])&&b.term){for(var c=Math.min(m,e),e=Math.max(m,e),p=[],d=c;d<=e;d++)(b=k.items[d])&&p.push(b.term);for(var b=p.join(" "),h=k.selectedTerms||[],d=0;d<p.length;d++){var t=p[d],
w=h.indexOf(t);-1!=w?t!=g?y(h,t):h.splice(w,1,b):q(h,b)}C=b;k.selectedTerms=h;for(d=e;d>c;d--)k.items.splice(d,1);k.items.splice(c,1,{term:b});for(d=0;d<k.items.length;d++)if(k.items[d].term==b){m=D=d;break}G(k,function(){l(k)})}}else S?H(a,!1):z(a,!1)}a.preventDefault();return!1},!0);r.addEventListener("mouseup",function(a){if("INPUT"!=a.target.tagName){if(0==a.button&&-1!=m){var d=!0,c=k.selectedTerms||[],b=k.items[m].term;if(!C&&N){for(var e=c.indexOf(b),b=0;b<k.items.length;b++){var f=k.items[b].term;
-1==e?q(c,f):y(c,f)}k.selectedTerms=c;d=!1}else if(!C&&Q){e=R(b);if(1<e.length)for(y(c,b),k.selectedTerms=c,k.items.splice(m,1),b=e.length-1;0<=b;b--)k.items.splice(m,0,{term:e[b]});else K(a,!0);d=!1}G(k,function(){l(k,d)});m=-1}a.preventDefault();return!1}},!0);r.addEventListener("mousewheel",function(a){if(-1!=D&&80<=a.timeStamp-W&&80<=Math.abs(a.wheelDelta)){var d=k&&k.items&&k.items[D];if(d=d&&d.term)window.find(d,!1,!(0<=a.wheelDelta),!0),W=a.timeStamp}a.preventDefault();return!1},!0);document.addEventListener("visibilitychange",
function(){if(null!==M){var a=M;a.length?E.applyItems(a):E.remove();M=null}},!1);chrome.storage.onChanged.addListener(F);l(h);r.ondragover=function(a){a.preventDefault()};r.ondrop=function(a){a.preventDefault();U(a.dataTransfer.getData("Text"));v&&I()};x.monitor("querybar-color-list",function(){l(k)})}function Z(h,f){var l={},n={},x=document.getElementById(h)||document.body,v=f||"EM",z=new RegExp("^(?:"+v+"|SCRIPT|STYLE)$"),q="";this.setMatchType=function(b){switch(b){case "left":this.openLeft=!1;
this.openRight=!0;break;case "right":this.openLeft=!0;this.openRight=!1;break;case "open":this.openLeft=this.openRight=!0;break;default:this.openLeft=this.openRight=!1}};this.setRegex=function(b,f){function h(b){b=b.replace(/\\/g,"\\\\");b=b.replace(/\^/g,"\\^");b=b.replace(/\$/g,"\\$");b=b.replace(/\./g,"\\.");b=b.replace(/\|/g,"\\|");b=b.replace(/\?/g,"\\?");b=b.replace(/\*/g,"\\*");b=b.replace(/\+/g,"\\+");b=b.replace(/\(/g,"\\(");b=b.replace(/\)/g,"\\)");b=b.replace(/\[/g,"\\[");return b=b.replace(/\{/g,
"\\{")}try{b=h(b).replace(/\s+/g,"|");if(f)for(var l=0;l<f.length;l++)b+=(b.length?"|":"")+h(f[l]);l="("+b+")";this.openLeft||(l="\\b"+l);this.openRight||(l+="\\b");q=new RegExp(l,"i")}catch(n){console.log("Error in setRegex: "+(n&&n.message))}};this.setRegexTerms=function(b){for(var f=[],h=[],l=0;l<b.length;l++){var n=b[l].trim();n.match(/\s/)?h.push(n):f.push(n)}this.setRegex(f.join(" "),h)};this.getRegex=function(){var b=q.toString(),b=b.replace(/(^\/(\\b)?|\(|\)|(\\b)?\/i$)/g,"");return b=b.replace(/\|/g,
" ")};this.hiliteWords=function(b){if(void 0!=b&&b&&q&&!z.test(b.nodeName)&&"ra-querybar"!=b.id){if(b.hasChildNodes())for(var f=0;f<b.childNodes.length;f++)this.hiliteWords(b.childNodes[f]);if(3==b.nodeType&&(nv=b.nodeValue)&&(regs=q.exec(nv))){f=document.createElement(v);f.appendChild(document.createTextNode(regs[0]));var h=regs[0].toLowerCase();f.style.backgroundColor=l[h]||"#f99";f.style.color=n[h]||"#000";h=b.splitText(regs.index);h.nodeValue=h.nodeValue.substring(regs[0].length);b.parentNode.insertBefore(f,
h)}}};this.remove=function(){for(var b=document.getElementsByTagName(v);b.length&&(el=b[0]);){var f=el.parentNode;f.replaceChild(el.firstChild,el);f.normalize()}};this.applyItems=function(b){this.remove();if(b&&b.length){var f=[];l={};n={};for(var h=0;h<b.length;h++){f.push(b[h].term);var q=b[h].term.toLowerCase();l[q]=b[h].color;n[q]=b[h].textColor}f.sort(function(b,f){return b.length<f.length?1:-1});this.setRegexTerms(f);this.hiliteWords(x)}}}var n=document.URL;if(-1==n.indexOf("://www.raterhub.com")&&
-1==n.indexOf("://www.rateraide.com/test")&&-1==n.indexOf("://www.rateraide.com/web")&&-1==n.indexOf("://our.intern.facebook.com")&&-1==n.indexOf("://player.siriusxm.com")&&-1==n.indexOf("://www.netflix.com/watch/")&&-1==n.indexOf("://e32.ultipro.com"))if(-1!=n.indexOf("://www.leapforceathome.com"))document.addEventListener("DOMContentLoaded",function(h){(h=document.querySelector("table#layout-table td.left-column a.alias"))&&(h=(h.textContent||"").trim())&&chrome.runtime.sendMessage({type:"got-social-alias",
alias:h})});else{var H=document.getElementById("ra-querybar");H&&H.parentNode.removeChild(H);var F=0,z=0;chrome.runtime.onMessage.addListener(function(h){if("set-label"==h.type&&h.label){var f=document.title.replace(/^(((L|R|A|B)(\d+|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z)(\/?(L|R|A|B)(\d+|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z))?|(Live|Cache)?)( - )?)/,"");h.label&&(f=h.label+(f.length?" - "+f:""));F=0;z&&clearInterval(z);z=setInterval(function(){document.title!=f?(document.title=
f,F=0):6<++F&&(clearInterval(z),z=0)},500);document.title&&document.title!=f&&(document.title=f);if(document.hidden&&-1!=document.URL.indexOf("youtube.com")){h=document.getElementsByClassName("ytp-play-button");for(var l=0;l<h.length;l++)"Pause"==h[l].getAttribute("aria-label")&&h[l].click()}}});if(-1==n.indexOf("manualslib.com/manual/")&&-1==n.indexOf(".com/mobile/")&&-1==n.indexOf("www.jjsulin.com")&&-1==n.indexOf("presidency.ucsb.edu")&&-1==n.indexOf("youtube-nocookie.com")){var J=atob("c3Vic2NyaXB0aW9u"),
x={initialize:function(h){chrome.storage.onChanged.addListener(function(f,h){if(f["querybar-color-list"]&&(x._prefs["querybar-color-list"]=f["querybar-color-list"].newValue,x.monitors&&x.monitors["querybar-color-list"]))x.monitors["querybar-color-list"]()});chrome.storage.local.get("querybar-color-list",function(f){x._prefs=f;h&&h()})},get:function(h){return x._prefs[h]},monitor:function(h,f){x.monitors||(x.monitors={});x.monitors[h]=f},_prefs:{}},v=!1,L=!0,l=null;x.initialize(function(){});"complete"==
document.readyState?I():document.addEventListener("DOMContentLoaded",I,!1)}}})();
