var INVOICE_SELECT_URL="https://www.raterlabs.com/qrp/core/vendors/invoices",DATE_FORMAT="M/D/YY",DID_FILL_TIMECARD=!1,EXISTING_ENTRIES_KEY="ra-invoice-existing-entries",PACIFIC_TIMEZONE="America/Los_Angeles",REFILL_KEY="ra-invoice-refill",WILL_SAVE_KEY="ra-invoice-will-save";String.prototype.hashCode=function(){var b=0,c,a,d;if(0==this.length)return b;c=0;for(d=this.length;c<d;c++)a=this.charCodeAt(c),b=(b<<5)-b+a,b|=0;return b};var _v_=atob("c3Vic2NyaXB0aW9u");
function cancelRefill(){localStorage.removeItem(REFILL_KEY)}function clearTableRowHighlighting(b){b.find("td").removeClass("ra-red ra-yellow ra-green")}function clearTableHighlighting(){$("tr.invoice-entry").each(function(){clearTableRowHighlighting($(this))})}function isShowingError(){return!!$("#error-wrapper:visible").length}function handleSaveButtonClick(){DID_FILL_TIMECARD&&localStorage.setItem(WILL_SAVE_KEY,Date.now())}
function getExistingEntries(){var b={};$("tr.invoice-entry:visible").each(function(c){if(!isTrainingRow($(this))){c=$(this).find("input.date-picker:visible").first();var a=moment(c.val());if(a.isValid()){c=parseInt($(this).find("select.hours-minutes-picker").eq(0).val(),10);var d=parseInt($(this).find("select.hours-minutes-picker").eq(1).val(),10);isNaN(c)||isNaN(d)||(a=a.format(DATE_FORMAT),b[a]={hour:c,minute:d})}}});return b}
function getPeriod(){var b=$('h2:contains("Pay\tperiod")').text().trim();b||(b=$('select[name="selectedPeriodStart"]').find("option:selected").text());if(b=/\d\d\/\d\d\/\d\d\d\d\s-\s\d\d\/\d\d\/\d\d\d\d/.exec(b)){var c=b[0].split("-");if(2<=c.length){var b=moment(c[0]),c=moment(c[1]).add(1,"d"),a=moment.tz.zone(PACIFIC_TIMEZONE),d=moment.tz.zone(moment.tz.guess()),a=a.offset(b)-d.offset(b);b.add(a,"m");c.add(a,"m");return[b.valueOf(),c.valueOf()]}console.log("Error: Invalid date components")}else console.log("Error: Invalid date format");
return null}
function performFill(b){var c=getPeriod();c||b.notify_only?chrome.runtime.sendMessage({method:"fetch-between",head:c[0],tail:c[1]},function(a){console.log("Fetched "+Object.keys(a.sessions).length+" session(s).");a.active&&a.active.start>=c[0]&&a.active.stop<c[1]&&(a.sessions[a.active.sid]=a.active);var d=[];$.each(a.sessions,function(b,c){var a=moment(c.start).tz(PACIFIC_TIMEZONE),f=a.format(DATE_FORMAT),g=!1;$.each(d,function(b,a){if(a.dateStr==f)return g=!0,a.duration+=c.duration,a.sessions.push(c),!1});
g||d.push({duration:c.duration,date:a,dateStr:f,sessions:[c]})});var g={},l={},m={};$("tr.invoice-entry:visible").each(function(b){if(isTrainingRow($(this)))g[b]=1;else{var a=$(this).find("input.date-picker:visible").first(),c=!1,a=moment(a.val());if(a.isValid()){var c=!0,f=a.format(DATE_FORMAT);$.each(d,function(b,a){a.dateStr==f&&(c=!1)})}c&&(l[b]=1);$(this).find("select").each(function(){if(-1!=$(this).attr("name").indexOf("rateId"))return $(this),!1})}});var h=0,k=0;$("tr.invoice-entry:visible").each(function(a){if(!g[a]&&
!l[a])if(m[a]=1,d[h]){a=!1;var c=$(this).find("input.date-picker:visible").first(),e=d[h].date.format(DATE_FORMAT);c.val()!=e&&(b.notify_only||c.val(e),a=!0);var e=moment.duration(d[h].duration),c=Math.floor(e.asHours()),e=e.minutes(),f=$(this).find("select.hours-minutes-picker:visible").eq(0);f.val()!=c&&(b.notify_only||f.val(c),a=!0);c=$(this).find("select.hours-minutes-picker:visible").eq(1);c.val()!=e&&(b.notify_only||c.val(e),a=!0);a&&k++;h++}else return!1});console.log("Found "+k+" change(s) for "+
h+" of "+d.length+" row(s).");console.log("Have "+Object.keys(m).length+" usable rows.");a=Math.max(0,d.length-Object.keys(m).length);var n=!1;b.notify_only||(0<a?n=!0:cancelRefill(),chrome.storage.local.get(EXISTING_ENTRIES_KEY,function(a){var b=a[EXISTING_ENTRIES_KEY]||{};$("tr.invoice-entry:visible").each(function(){if(!isTrainingRow($(this))){var a=$(this).find("input.date-picker").first(),c=b[a.val()];if(c){var a=parseInt($(this).find("select.hours-minutes-picker").eq(0).val(),10),d=parseInt($(this).find("select.hours-minutes-picker").eq(1).val(),
10);c.hour==a&&c.minute==d||$(this).find("td").addClass("ra-yellow")}else a.val()&&$(this).find("td").addClass("ra-green")}})}),$("tr.invoice-entry:visible").each(function(a){a=$(this).find("input.date-picker").first();moment(a.val()).isValid()||$(this).find('input[name="deleteRow"]').click()}));b.notify_only?0==a&&0==k&&$.notify("Timecard is up to date!",{className:"success",autoHide:!0}):Object.keys(l).length?$.notify("Warning: "+(1==unworkableRowCount?"One row has":"Multiple rows have")+" no billable sessions.",
{className:"error",autoHide:!0}):0==a&&0<k?$.notify("Updated timecard! Review changes and save draft.",{className:"success",autoHide:!0}):0==a&&0==k&&$.notify("Timecard is up to date!",{className:"success",autoHide:!0});n&&performRefill()}):(cancelRefill(),INVOICE_SELECT_URL!=document.URL&&$.notify("Error: Could not determine pay period.",{className:"error",autoHide:!1}))}function performRefill(){localStorage.setItem(REFILL_KEY,"true");$('input[name="addRow"]').click()}
function v(b){chrome.storage.local.get(_v_,function(c){b(!!(c[_v_]&&"active"==c[_v_].status||"trialing"==c[_v_].status))})}function dialogCloser(b){$(".ui-dialog-titlebar-close:visible").first().length?$(".ui-dialog-titlebar-close:visible").first().click():50>b&&setTimeout(dialogCloser,100,++b)}function isTrainingRow(b){return b.find('input[value="TRAINING"]:visible').prop("checked")}
if(INVOICE_SELECT_URL==document.URL)chrome.storage.local.set({"uses-raterlabs":!0});else if(-1!=document.URL.indexOf("qrp/core/vendors/invoice")){var start=function(){0==$(".ra-fill").length&&$('input[name="addRow"]').parent().append('<input class="ra-fill" type="button" value="Fill Using RaterAide" style="display:none" disabled=true>');v(function(b){b?($('input[name="save"]').on("click",handleSaveButtonClick),$(".ra-fill").attr("disabled",!1).show()):($('input[name="save"]').off("click",handleSaveButtonClick),
$(".ra-fill").attr("disabled",!0).show())})};$(document).on("click",".ra-fill",function(){var b={};b[EXISTING_ENTRIES_KEY]=getExistingEntries();v(function(c){c?(chrome.storage.local.set(b,function(){clearTableHighlighting();cancelRefill();performFill({notify_only:!1})}),DID_FILL_TIMECARD=!0):$(".ra-fill").attr("disabled",!0)})});$(document).on("click",".ra-clear",function(){clearTableHighlighting()});if("true"==localStorage.getItem(REFILL_KEY))console.log("Performing re-fill..."),performFill({notify_only:!1});
else if(localStorage.getItem(WILL_SAVE_KEY)){var elapsed=Date.now()-localStorage.getItem(WILL_SAVE_KEY);localStorage.removeItem(WILL_SAVE_KEY);1E4>elapsed&&(isShowingError()||$.notify("Saved timecard!",{className:"success",autoHide:!0}))}else INVOICE_SELECT_URL==document.referrer&&performFill({notify_only:!0});chrome.storage.onChanged.addListener(function(b){b[_v_]&&start()});start()}else if(-1!=document.URL.indexOf("vendors/needs_met_feedback")||-1!=document.URL.indexOf("vendors/needs_met_simulator")){var sendLinksToRaterAide=
function(b){var c={left:[],right:[]},a=$("#bu-sim-header").nextAll("table").first().find("table");a.eq(0).find("div.bu-sim-html").each(function(a){if(!$(this).closest("tr").prev("tr").find(".sliders-noscore-overlay:visible").length){var b=$(this).find("a").first().attr("href");b&&c.left.push({id:"left.result."+a,index:a,label:"L"+(1+a),title:(is_feedback?"Feedback":"Simulator")+" Link",type:"WEB",url:b})}});a.eq(1).find("div.bu-sim-html").each(function(a){if(!$(this).closest("tr").prev("tr").find(".sliders-noscore-overlay:visible").length){var b=
$(this).find("a").first().attr("href");b&&c.right.push({id:"right.result."+a,index:a,label:"R"+(1+a),title:(is_feedback?"Feedback":"Simulator")+" Link",type:"WEB",url:b})}});if(c.left.length||c.right.length)if(a=$("#bu-sim-header b").first().text().trim())document.URL.match(/\d+$/)&&document.URL.match(/\d+$/),a={acquireTime:Date.now(),blocks:c,nonce:Date.now(),query:a,simulator:!0,taskId:a.hashCode().toString()},port.postMessage({method:"got-s2d-features",data:a,notify:!!b,sim:!0})},port=chrome.runtime.connect({name:"ra-features"});
port.onMessage.addListener(function(b){"close-s2d-dialog"==b.method&&dialogCloser(0)});(function addHeaderLink(c){var a=$("#bu-sim-sub-header");a.length?a.after('<div style="padding:8px 16px 8px 8px; font-size: 20px; background-color: #e9f2fc; border: 1px solid #cccccc; border-top: none; -webkit-user-select:none; user-select: none"><a id="send-to-ra" style="cursor: pointer">Send to RaterAide</a><div>'):10>c++&&setTimeout(addHeaderLink,100,c)})(0);$(document).on("click","a",function(){if($(this).closest("div.bu-sim-html").length){var b=
$(this).attr("href");b&&port.postMessage({method:"send-to-device",url:b})}});var is_feedback=-1!=document.URL.indexOf("needs_met_feedback");$(document).on("click","#send-to-ra",function(){sendLinksToRaterAide(!0)});chrome.storage.local.get([_v_,"is-active"],function(b){b[_v_]&&!b["is-active"]&&sendLinksToRaterAide(!1)})};
